version: "2.2"
services:
 
  iris:
    init: true
    container_name: iris
    build:
      context: iris
    ports:
      - 52773:52773
      - 51773:51773
      - 22026:22026
    volumes:
      - ./shared:/shared

  tools:
    build:
      context: tools
    container_name: tools
    volumes:
      - ./shared:/shared