services:

  # iris container
  iris:
    init: true
    container_name: iris
    build:
      context: iris
    ports:
      - 52773:52773
      - 1972:1972
    volumes:
      - ./shared:/shared

  # tools container: DICOM simulator
  tools:
    build:
      context: tools
    container_name: tools
    volumes:
      - ./shared:/shared

  # sample external database to integrate from InterSystems IRIS interoperability framework  
  mysql:
    build:
      context: mysql
      dockerfile: Dockerfile
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - "3306:3306"