version: "2.2"
services:
 
  # iris container
  iris:
    init: true
    container_name: iris
    command: --check-caps false
    build:
      context: iris
    ports:
      - 52773:52773
      - 1972:1972
    volumes:
      - ./shared:/shared

  # tools container: DICOM simulator
  tools:
    build:
      context: tools
    container_name: tools
    volumes:
      - ./shared:/shared